### ISSUE TITLE
Add annotations to add more details in configuration metadata 

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#176]
**Is your feature request related to a problem? Please describe.**
In order to have more details for other users to understand the application, the configuration should allow for additional standardized fields.  This will allow for all component developers to communicate their application descriptions and details in the same way.

**Propose a solution**
Add `annotations` in the metadata: (all optional)
```yaml
metadata:
  version: 0.1.0
  annotations:
    authors: --names of individuals (array of strings)
    vendors: --company or organization names (array of strings)
    description: --short description of component or application
    documentation: --link to documentation
    licenses: --any license or restrictions
    icon: --local path to icon
```

**Describe alternatives you've considered**
It could be perhaps part of another file that is imported to the configuration.

```yaml
metadata:
  version: 0.1.0
  annotations_file: ./annotations.yaml
```

`annotations.yaml`
```yaml
---
kind: wick/annotations@v1
annotations:
  authors: --names of individuals (array of strings)
  vendors: --company or organization names (array of strings)
  description: --short description of component or application
  documentation: --link to documentation
  licenses: --any license or restrictions
  icon: --local path to icon
```
**Additional context**
None
