### ISSUE TITLE
LocationReference values in config don't support environment variable substitution.

### ISSUE THREAD

**Issue by jsoverson** [candlecorp/wick#180]
**Describe the bug**
Using env variables like `$PWD` to refer to assets in configuration doesn't work.

**To Reproduce**
Try to run a component referenced like this:

```yaml
kind: wick/component@v1
component:
  kind: wick/component/composite@v1
  import:
    - name: test
      component:
        kind: wick/component/manifest@v1
        ref: $PWD/test.fake.wasm
  operations: []
```

**Expected behavior**
Wasm should import fine (if it actually exists)

**Actual behavior**
$PWD never gets substituted to wasm doesn't load.

**Environment:**
 - OS: mac 
 - Architecture: m1
 - Build Version: b83485305d609f9f599ae4a3f0aa03d9e101fb5c
