### ISSUE TITLE
Component relative path not found

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#189]
**Describe the bug**
Unable to find the component using relative path.

**To Reproduce**
put this in `wick/examples/serve_static_http` directory as `app.wick`.
```
---
kind: wick/app@v1
name: serve_static_http
metadata:
  description: Serve static files over HTTP
  version: 0.0.1
  authors:
    - "Wick Maintainers"
  vendors:
    - "Candle Corporation"
  licenses:
    - Apache-2.0
resources:
  - name: http
    resource:
      kind: wick/resource/tcpport@v1
      port: 8999
      address: 0.0.0.0
triggers:
  - kind: wick/trigger/http@v1
    resource: http
    routers:
      - kind: wick/router/raw@v1
        path: /
        operation:
          name: http_handler
          component:
            kind: wick/component/manifest@v1
            ref: ../../crates/integration/test-http-trigger-component/component.yaml
```

From  `wick/examples/serve_static_http` run `wick run app.wick`

**Expected behavior**
It should start the application successfully.

**Actual behavior**
It is unable to find the component.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**
