### ISSUE TITLE
Add simplified support for list in types

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#200]
**Is your feature request related to a problem? Please describe.**
I would like the ability to not have to use a complex object structure to define my types when expecting a list of outputs/inputs.
```yaml
      outputs:
        - name: result
          type: boolean
        - name: output
          type: string
        - name: captures
          type: { list: { type: string } }
          optional: true
```

**Propose a solution**
Ideally, I can do this:
```yaml
      outputs:
        - name: result
          type: boolean
        - name: output
          type: string
        - name: captures
          type: "[string]"
          optional: true
```

**Describe alternatives you've considered**
None

**Additional context**
None
