### ISSUE TITLE
Import functionality for types from existing app/component

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#210]
**Is your feature request related to a problem? Please describe.**
Add a `ref` in types and be able to pass a component or app reference (local or from registry/remote) to add a type from an existing component or app.

The remote app/component will be downloaded, parsed and the types will be made available to the new application/component.

**Propose a solution**

```yaml
...
component:
  imports:
    - kind: wick/types@v1
      name: HttpMethod 
      ref: registry.candle.dev/common/http
    - kind: wick/types@v1
      name: HttpScheme
      ref: registry.candle.dev/common/http
    - kind: wick/types@v1
      name: *
      ref: registry.candle.dev/common/http //just get them all
```

**Describe alternatives you've considered**
What are other things that would need to be imported?  Should types be its own file type as well?

**Additional context**
N/A
