### ISSUE TITLE
Volume Resource needs Path normalization

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#224]
**Describe the bug**
Relative path for volume resource is not relative to `app.wick`.

**To Reproduce**
```yaml
---
kind: wick/app@v1
name: serve_http_component
metadata:
  description: Serve static files with Wick
  version: 0.0.1
  authors:
    - "Wick Maintainers"
  vendors:
    - "Candle Corporation"
  licenses:
    - Apache-2.0
resources:
  - name: http
    resource:
      kind: wick/resource/tcpport@v1
      port: 8082
      address: 0.0.0.0
  - name: DIR
    resource:
      kind: wick/resource/volume@v1
      path: ./www/
triggers:
  - kind: wick/trigger/http@v1
    resource: http
    routers:
      - kind: wick/router/static@v1
        path: /
        volume: DIR
```

have appropriate directory (www) in the same parent directory as the `app.wick`
go up one directory and run the app.  It will not be able to find the static.

**Expected behavior**
It should normalize the `./www` path based on the relative path from the app.wick.

**Actual behavior**
It normalizes the `./www` path from the cli path where wick execution occurred.

**Environment:**
 - OS: OSX
 - Architecture: M1
 - Build Version: 0.6.0-Nightly

**Additional context**
None
