### ISSUE TITLE
`wick init` produces some config values as `null` when they should be omitted instead.

### ISSUE THREAD

**Issue by jsoverson** [candlecorp/wick#228]
**To Reproduce**
`wick init -c some_name`

**Expected behavior**
Produces a minimal, intuitive config.

**Actual behavior**
Produces configs with nulls and unnecessary defaults.

```
name: some_name
metadata: null
host:
  allow_latest: false
  timeout: 0
  rpc: null
component:
  kind: wick/component/composite@v1
package: null
```
