### ISSUE TITLE
Error responses to rest router should result in non-200 responses

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#249]
**Is your feature request related to a problem? Please describe.**
In my wasmrs component, when an error occurs I call this code:
```
outputs.output.error("error logging in user");
```

**Propose a solution**
This should indicate to the end user that there was an error.  Currently what happens is that the end user is returned a 200 OK with an empty payload `{}`. It would be nicer if the user was given a non-200 error. Ideally it could be configured in the route so it says 
```yaml
          - uri: "/user/login"
            operation: user::login
            methods:
              - POST
            description: "login user"
            on_error:
              status: 401
...
```

**Describe alternatives you've considered**
None

**Additional context**
None
