### ISSUE TITLE
SQL string returning empty trailing characters

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#250]
**Describe the bug**
I am using rest router to call a SQL component. The sql database column is a varchar(50). When I get my response, I am getting:
```
"cookies                                           "
```
which is exactly 50 characters long.

**To Reproduce**
get a string response:
DB config:
```
item              CHAR(50) NOT NULL
```
db.wick component
```yaml
    - name: get_top_items
      inputs:
        - name: user_id
          type: i32
      outputs:
        - name: output
          type: object
      query: |
        SELECT item, count(1) count
        FROM items
        WHERE transaction_id in (
          select id from transactions where card_id in 
            (select card_id from users where id = $1)
        )
        GROUP BY item
        ORDER BY count(1) DESC LIMIT 5;
      arguments:
        - user_id
```
rest router config
```yaml
          - uri: "/user/{user_id:i32}/transactions/top-items"
            operation: DEMODB::get_top_items
            methods:
              - GET
            description: "login user"
```

**Expected behavior**
string without trailing spaces

**Actual behavior**
string with trailing spaces

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**
