### ISSUE TITLE
wick registry push not including wasm files from imported local components

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#256]
**Describe the bug**
The wasm asset of an imported component is not pushed when a parent component is pushed to the registry.

**To Reproduce**
component.wick:
```yaml
---
kind: wick/component@v1
name: "jinja"
metadata:
  version: "2"
  icon: "./assets/icon.png"
import:
  - name: include
    component:
      kind: wick/component/manifest@v1
      ref: ./include.wick
package:
  files:
    - ./assets/**/*
  registry:
    registry: $DOCKER_REGISTRY
    namespace: default
component:
  kind: wick/component/composite@v1
  operations:
    - name: test-component
      inputs:
        - name: input
          type: string
      outputs:
        - name: output
          type: string
      flow:
        - <>.input -> <>.output
```
include.wick
```yaml
---
kind: wick/component@v1
name: "include"
metadata:
  version: "3"
component:
  kind: wick/component/wasmrs@v1
  ref: ./assets/test.fake.wasm
```

**Expected behavior**
The test.fake.wasm should be present in the pushed package

**Actual behavior**
the test.fake.wasm is not present in the pushed package

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**
