### ISSUE TITLE
HTTP Middleware

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#270]
**Is your feature request related to a problem? Please describe.**
There should be middleware for HTTP requests.

**Propose a solution**
The middleware should be added to routers and have a specific interface:
a `middleware` section should be added to all routers as an array of operations and should execute top down on request and bottom-up on response.

```yaml
triggers:
  - kind: wick/trigger/http@v1
    resource: http
    routers:
      - kind: wick/router/rest@v1
        middleware:
          - oauth2 #just the component name.
        path: /api/
        routes:
          - uri: "/"
            operation: transaction::insert
            methods:
              - POST
            description: "Insert new transaction"
      - kind: wick/router/proxy@v1
        middleware:
          - oauth2
          - whitelist
        path: /home
        url: PROXY_URL
      - kind: wick/router/static@v1
        middleware:
          - whitelist
        path: /
        volume: DIR
        fallback: index.html
```

The input/output types for middleware should be as follows: Middleware components must have a `on_request` and `on_response` operation with the exact type match.

```yaml
name: oauth2
component:
    kind: wick/component/...@v1
    ref: ...
    operations:
      - name: on_request
        inputs:
          - name: input
            type: HttpRequest
        outputs:
          - name: output
            type: HttpRequest || HttpResponse
      - name: on_response
        inputs:
          - name: input
            type: HttpResponse
        outputs:
          - name: output
            type: HttpResponse
```

**Describe alternatives you've considered**
None

**Additional context**
None
