### ISSUE TITLE
Components should allow resources to be passed as "requires"

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#279]
**Is your feature request related to a problem? Please describe.**
Resources should be able to be separated from components and applications. This would allow for better devops control and environmental changes. 

**Propose a solution**
Components should be able to `require` an resource.  This way the resources are not tied to the component.  The component can then expect the resource to be provided to them without having to manage the component itself.  By using the `requires` interface, it keeps the integration to components consistent.

```yaml
name: oauth_db
kind: wick/component@v1
requires:
  - name: DBADDR
     kind: wick/resource/url@v1
  - name: other_component
     kind: wick/interface@v1
     operations:
        - name: do_something
           inputs:
             - name: something
                type: string
           outputs:
             - name: bar
                type: string
component:
  kind: wick/component/sql@v1
  resource: DBADDR
  tls: false
  operations:
    - name: insert_card
      inputs:
        - name: card_number
          type: string
        - name: card_type
          type: string
      outputs:
        - name: output
          type: object
      query: |
        INSERT INTO cards (card_number, card_type)
        VALUES ($1, $2)
        ON CONFLICT (card_number) DO UPDATE SET card_number = cards.card_number
        RETURNING id
      arguments:
        - card_number
        - card_type
```

**Describe alternatives you've considered**
None

**Additional context**
None
