### ISSUE TITLE
HTTP Types too many requirements

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#292]
**Describe the bug**
I was using http types to build a test and it was very explicit that it needed many fields that should be optional:

**To Reproduce**
```yaml
- name: input
            data:
              method: Get
              scheme: Http
              path: "/"
              uri: "http://localhost:8080/"
              version: Http11
              headers:
                host:
                  - "localhost:8080"
                user-agent:
                  - "curl/7.64.1"
                accept:
                  - "*/*"
                cookie:
                  - "sessionid=1234"
```

**Expected behavior**
I shouldn't need to enter query_parameters at all.

**Actual behavior**
I had to do this:
```yaml
- name: input
            data:
              method: Get
              scheme: Http
              path: "/"
              uri: "http://localhost:8080/"
              version: Http11
              authority: "localhost:8080"
              query_parameters: {}
              headers:
                host:
                  - "localhost:8080"
                user-agent:
                  - "curl/7.64.1"
                accept:
                  - "*/*"
                cookie:
                  - "sessionid=1234"
```

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**
