### ISSUE TITLE
Wick test for stream of responses

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#306]
**Is your feature request related to a problem? Please describe.**
When I run `wick test`, it expects a single value response.  My component creates a stream of responses.  How can I test for multiple responses in a stream?

**Propose a solution**
Expose characteristics of the response, like "length" so I can make sure that if I expect 4 outputs for the stream, I can test for that.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fawadasaurus** [comment]
Thanks.

This worked:
```yaml
  - name: test_each
    cases:
      - name: simple array
        operation: each
        inputs:
          - name: input
            value: [1,2,3]
        outputs:
          - name: output
            value: 1
          - name: output
            value: 2
          - name: output
            value: 3
          - name: output
            flags:
              done: true
```
