### ISSUE TITLE
Import components inconsistent behavior

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#310]
**Describe the bug**
Sometimes I need a `@` in the component and other times I don't.

**To Reproduce**
```yaml
import:
  - name: liquid_json
    component:
      kind: wick/component/manifest@v1
      ref: '@registry.candle.dev/common/liquid-json:0.1.0'
```
adding this to a config will have it work using `wick run` but it will not work with `wick test`

**Expected behavior**
registry should not need `@` before it.

**Actual behavior**
registry sometimes needs `@` before it.

**Environment:**
 - OS
 - Architecture
 - Build Version

**Additional context**
