### ISSUE TITLE
Splat array inputs for SQL components

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#313]
**Is your feature request related to a problem? Please describe.**
Need a way to shortcut operations (such as sql operations) that have a very large number of inputs.

**Propose a solution**
Current implementation
```yaml
- name: insert_record
  inputs:
    - name: col1
      type: string
    - name: col2
      type: string
    - name: col3
      type: string
    - name: col4
      type: string
    - name: col5
      type: string
    - name: col6
      type: string
    - name: col7
      type: string
    - name: col8
      type: string
    - name: col9
      type: string
    - name: col10
      type: string
    - name: col11
      type: string
  query: |-
    insert into mytable(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11)
    values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
  arguments:
    - col1
    - col2
    - col3
    - col4
    - col5
    - col6
    - col7
    - col8
    - col9
    - col10
    - col11
  on_error: Ignore
```

This passes the inputs into the arguments in the order that the inputs are defined above. The types are enforced by the input definition and passing the wrong value types are handled by wick.

here the * is an array of the values of the defined inputs.
```yaml
- name: insert_record
  inputs:
    - name: col1
      type: string
    - name: col2
      type: datetime
    - name: col3
      type: i32
    - name: col4
      type: f32
    - name: col5
      type: string
    - name: col6
      type: string
    - name: col7
      type: string
    - name: col8
      type: string
    - name: col9
      type: string
    - name: col10
      type: datetime
    - name: col11
      type: datetime
  query: |-
    insert into mytable(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11)
    values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
  arguments:
    - *
  on_error: Ignore
```

When you don't care and want to let the caller figure it out:
the inputs are expected to be an array of whatever and the query will fail if its not right.

Here values is the name of the input and if it is an array, it will pass each item in its array as the value for that position in the query.
```yaml
- name: insert_record
  inputs:
    - name: values
      type: object[]
  query: |-
    insert into mytable(col1, col2, col3, col4, col5, col6, col7, col8, col9, col10, col11)
    values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
  arguments:
    - values*
  on_error: Ignore
```

**Describe alternatives you've considered**
TBD
**Additional context**
TBD
