### ISSUE TITLE
`ctx.root_config` not accessible in operation instance template context.

### ISSUE THREAD

**Issue by jsoverson** [candlecorp/wick#334]
**Describe the bug**
Using `{{ctx.root_config.XXX}}` in an operation instance `with` block results in an error.

**To Reproduce**

Invoke/run something with an operation instance that has configuration like:

```yaml
---
kind: wick/component@v1
name: test
component:
  kind: wick/component/composite@v1
  with: 
    - name: token
      type: string
  operations:
    - name: mail_send
      uses:
        - name: CONFIG
          operation: core::sender
          with: 
            output:
              token: '{{ ctx.root_config.token }}'
```

**Expected behavior**
The op config gets rendered with the root token.

**Actual behavior**
Error occurs, complaining about `unknown index`

**Environment:**
 - OS: mac
 - Architecture: m1
 - Build Version: head
