### ISSUE TITLE
ENV resource from file

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#349]
**Is your feature request related to a problem? Please describe.**
Currently, the application has access to all environment variables.  This is not ideal as all other resources are explicitly defined ahead of time.  This is also valuable in deployment scenarios where a single secret can be stored and mounted as a filesystem directory instead of passing multiple individual secrets as environment variables to each deployed container.

**Propose a solution**
Environment variables should have a resource definition just like ports and file system.

```yaml
resources:
  - name: env
    resource:
      kind: wick/resource/environment@v1
      vars_from:
        file:
          - .env
          - /root/.zshrc
        env:
          - ABC
          - MY_ENV_VAR
```

**Describe alternatives you've considered**
None

**Additional context**
None
