### ISSUE TITLE
Ordered Flow

### ISSUE THREAD

**Issue by fawadasaurus** [candlecorp/wick#397]
**Is your feature request related to a problem? Please describe.**
I need to run an operation after other operations have completed.

```yaml
component:
  kind: wick/component/composite@v1
  with:
    - name: db_url
      type: string
  operations:
  - name: migration_1
    uses:
      - name: COMPLETE_MIGRATION
        operation: candle_cloud_db::complete_migration
    flow:
    - candle_cloud_db::create_migrations_table.output -> drop
    - candle_cloud_db::create_users_table.output -> drop
    - candle_cloud_db::create_oauth_sessions_table.output -> drop
    - candle_cloud_db::create_oidc_claims_table.output -> drop
    - candle_cloud_db::create_tenants_table.output -> drop
    - candle_cloud_db::create_tenant_users_table.output -> drop
    - candle_cloud_db::create_deployments_table.output -> drop
    - candle_cloud_db::create_secrets_table.output -> drop
    - <>.name -> COMPLETE_MIGRATION.name
    - COMPLETE_MIGRATION.output -> <>.output
```

In this operation, I need to run `create_tenant_users_table` only after `create_tenants_table` and `create_users_table` completes.

**Propose a solution**
Make a `prereq` component that exists at the top level, similar to drop.
```yaml
component:
  kind: wick/component/composite@v1
  with:
    - name: db_url
      type: string
  operations:
  - name: migration_1
    uses:
      - name: CREATE_TENANT_USERS_TABLE
        operation: candle_cloud_db::create_tenant_users_table
      - name: COMPLETE_MIGRATION
        operation: candle_cloud_db::complete_migration
    flow:
    - candle_cloud_db::create_migrations_table.output -> drop
    - candle_cloud_db::create_users_table.output -> prereq.CREATE_TENANT_USERS_TABLE
    - candle_cloud_db::create_oauth_sessions_table.output -> drop
    - candle_cloud_db::create_oidc_claims_table.output -> drop
    - candle_cloud_db::create_tenants_table.output -> prereq.CREATE_TENANT_USERS_TABLE
    - CREATE_TENANT_USERS_TABLE.output -> drop
    - candle_cloud_db::create_deployments_table.output -> drop
    - candle_cloud_db::create_secrets_table.output -> drop
    - <>.name -> COMPLETE_MIGRATION.name
    - COMPLETE_MIGRATION.output -> <>.output
```

**Describe alternatives you've considered**
None

**Additional context**
None
